name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
          check-latest: true
      -
        name: Install dependencies
        run: |
          go version
          go install golang.org/x/lint/golint@latest
      -
        name: Run build
        run: go build cmd/main.go
      -
        name: Run vet & lint
        run: |
          go vet .
          golint .